import procurementIcon from './assets/procurement_icon.webp';
import digitalMarketingIcon from './assets/digital_marketing_icon.webp';
import retailMarketingIcon from './assets/retail_marketing_icon.webp';
import technicianIcon from './assets/technician_icon.webp';

export const initialJobs = [
  {
    id: "job-lg-4",
    title: "Kỹ thuật viên Dịch vụ Khách hàng (SVC Technician)",
    titleEn: "Customer Service Technician (SVC Technician)",
    company: "LG Electronics Việt Nam",
    companyEn: "LG Electronics Vietnam",
    logo: technicianIcon,
    location: "Đà Nẵng",
    locationEn: "Da Nang",
    salary: "700 - 1,100 USD",
    type: "Full-time",
    level: "Junior",
    industry: "Warranty Technician",
    description: "Thực hiện lắp đặt, bảo dưỡng, sửa chữa và khắc phục các sự cố kỹ thuật đối với sản phẩm LG (Tivi, Tủ lạnh, Điều hòa, Máy giặt) tại nhà khách hàng hoặc tại trung tâm dịch vụ kỹ thuật của LG.",
    descriptionEn: "Perform installation, maintenance, repair, and technical troubleshooting for LG products (OLED TV, Refrigerator, Air Conditioner, Washer) at customer locations or LG technical service centers.",
    requirements: "• Tốt nghiệp Trung cấp/Cao đẳng trở lên chuyên ngành Điện tử, Điện lạnh, Điện công nghiệp hoặc liên quan.\n• Ít nhất 1 năm kinh nghiệm sửa chữa thực tế các thiết bị gia dụng lớn (Home Appliances).\n• Thái độ làm việc trung thực, nhiệt tình, kỹ năng giao tiếp lịch sự với khách hàng.\n• Có phương tiện đi lại (xe máy) phục vụ công việc lưu động.",
    requirementsEn: "• Associate Degree or higher in Electronics, Refrigeration, Industrial Electrical Engineering, or related fields.\n• At least 1 year of practical repair experience with major Home Appliances.\n• Honest, enthusiastic work attitude with polite customer communication skills.\n• Own personal motorcycle for mobile field service travel.",
    benefits: "• Lương cứng ổn định + Phụ cấp xăng xe, điện thoại + Phụ cấp chuyên cần + Thưởng theo sản lượng SVC.\n• Được trang bị đầy đủ dụng cụ kỹ thuật cao cấp và đồng phục chính hãng.\n• Tham gia các khóa huấn luyện chuyên sâu định kỳ về công nghệ mới của LG.\n• Bảo hiểm tai nạn 24/7 và bảo hiểm y tế bắt buộc đầy đủ.",
    benefitsEn: "• Stable base salary + Petrol/Phone allowances + Attendance allowance + SVC yield performance bonuses.\n• Fully equipped with premium technical toolkits and genuine LG uniforms.\n• Periodic advanced training courses on LG's latest technologies.\n• 24/7 accident insurance and mandatory health insurance.",
    postedAt: "2026-08-04"
  },
  {
    id: "job-lg-1",
    title: "Chuyên viên Mua hàng Tập trung (Marketing Procurement Specialist)",
    titleEn: "Marketing Procurement Specialist",
    company: "LG Electronics Việt Nam",
    companyEn: "LG Electronics Vietnam",
    logo: procurementIcon,
    location: "TP. Hồ Chí Minh",
    locationEn: "Ho Chi Minh City",
    salary: "1,200 - 1,800 USD",
    type: "Full-time",
    level: "Middle",
    industry: "Marketing / PR",
    description: "Phụ trách các hoạt động mua sắm, đấu thầu tập trung cho các dịch vụ và tài liệu Marketing (POSM, Agency, sự kiện, media buying...) đảm bảo tối ưu hóa chi phí và tuân thủ quy trình của tập đoàn LG.",
    descriptionEn: "In charge of centralized procurement activities, agency bidding, POSM sourcing, event management, and media buying to ensure cost optimization and compliance with LG corporate procedures.",
    requirements: "• Tốt nghiệp Đại học chuyên ngành Kinh tế, Ngoại thương, Marketing hoặc liên quan.\n• Hơn 3 năm kinh nghiệm làm Mua hàng (Procurement/Buyer), đặc biệt ưu tiên kinh nghiệm mua hàng cho các hạng mục Marketing.\n• Kỹ năng đàm phán, thương lượng hợp đồng và quản lý nhà cung cấp tốt.\n• Tiếng Anh giao tiếp tốt (làm việc với quản lý người nước ngoài).",
    requirementsEn: "• Bachelor's Degree in Economics, International Trade, Marketing, or related fields.\n• 3+ years of Procurement/Buyer experience, preferably in Marketing category sourcing.\n• Strong contract negotiation, commercial terms evaluation, and vendor management skills.\n• Proficient English communication (working directly with expatriate managers).",
    benefits: "• Lương cứng cạnh tranh + Thưởng hiệu suất hàng năm (KPI Bonus).\n• Bảo hiểm sức khỏe PVI cao cấp dành riêng cho nhân viên LG.\n• Tham gia các khóa đào tạo chuyên sâu của tập đoàn.\n• Quà tặng và ưu đãi mua sắm sản phẩm điện máy LG.",
    benefitsEn: "• Highly competitive base salary + Annual KPI performance bonus.\n• Premium PVI private health insurance dedicated to LG employees.\n• Specialized corporate training & professional development programs.\n• Exclusive employee discount perks on LG home appliances & electronics.",
    postedAt: "2026-08-04"
  },
  {
    id: "job-lg-2",
    title: "Chuyên viên Digital Marketing",
    titleEn: "Digital Marketing Specialist",
    company: "LG Electronics Việt Nam",
    companyEn: "LG Electronics Vietnam",
    logo: digitalMarketingIcon,
    location: "TP. Hồ Chí Minh",
    locationEn: "Ho Chi Minh City",
    salary: "1,000 - 1,700 USD",
    type: "Full-time",
    level: "Middle",
    industry: "Marketing / PR",
    description: "Lên kế hoạch và thực thi các chiến dịch quảng cáo số (Facebook, Google, YouTube, TikTok) nhằm quảng bá các dòng sản phẩm gia dụng và giải trí cao cấp của LG (OLED TV, Tủ lạnh InstaView, Máy giặt WashTower).",
    descriptionEn: "Plan and execute digital performance advertising campaigns (Google Ads, Meta, YouTube, TikTok) to promote LG's premium home appliance and entertainment lineups (OLED TV, InstaView Refrigerator, WashTower).",
    requirements: "• Tối thiểu 3 năm kinh nghiệm chạy chiến dịch Digital Marketing hoặc làm việc tại các Agency quảng cáo lớn.\n• Thành thạo việc tối ưu hóa chuyển đổi, đọc số liệu Google Analytics, Facebook Pixel.\n• Tư duy sáng tạo, cập nhật xu hướng công nghệ số liên tục.\n• Kỹ năng giao tiếp và làm việc nhóm tốt.",
    requirementsEn: "• Minimum 3 years of experience running Digital Marketing campaigns or working at leading advertising agencies.\n• Proficient in conversion optimization, Google Analytics, and Facebook Pixel data analytics.\n• Creative mindset, constantly updating digital tech & social media trends.\n• Excellent communication and cross-functional teamwork skills.",
    benefits: "• Lương tháng 13 + Thưởng hiệu quả kinh doanh.\n• Hỗ trợ cơm trưa, phụ cấp điện thoại.\n• Khám sức khỏe định kỳ hàng năm tại các bệnh viện quốc tế.\n• Teambuilding và du lịch công ty hàng năm.",
    benefitsEn: "• 13th-month salary + Performance bonus.\n• Lunch allowance, mobile phone allowance.\n• Annual executive health checkups at top international hospitals.\n• Annual company teambuilding trips and retreats.",
    postedAt: "2026-08-03"
  },
  {
    id: "job-lg-3",
    title: "Chuyên viên Retail Marketing (Retail Marketing Specialist)",
    titleEn: "Retail Marketing Specialist",
    company: "LG Electronics Việt Nam",
    companyEn: "LG Electronics Vietnam",
    logo: retailMarketingIcon,
    location: "TP. Hồ Chí Minh",
    locationEn: "Ho Chi Minh City",
    salary: "1,000 - 1,600 USD",
    type: "Full-time",
    level: "Middle",
    industry: "Marketing / PR",
    description: "Chịu trách nhiệm lập kế hoạch và thực thi các chiến dịch Retail Marketing tại các đại lý, siêu thị điện máy (Thế Giới Di Động, Điện Máy Xanh, Nguyễn Kim...). Quản lý khu vực trưng bày sản phẩm (Brand Shop, Shop-in-shop), thiết kế và triển khai vật phẩm quảng cáo POSM đảm bảo hình ảnh thương hiệu LG nổi bật nhất.",
    descriptionEn: "Responsible for planning and executing Retail Marketing campaigns across retail partner chains (The Gioi Di Dong, Dien May Xanh, Nguyen Kim...). Manage product display areas (Brand Shop, Shop-in-Shop), design and deploy POSM materials to maximize LG brand visibility.",
    requirements: "• Tốt nghiệp Đại học chuyên ngành Marketing, Quản trị kinh doanh hoặc liên quan.\n• Tối thiểu 2 năm kinh nghiệm làm Retail Marketing, Trade Marketing trong ngành điện tử tiêu dùng, FMCG hoặc bán lẻ.\n• Kinh nghiệm quản lý nhà thầu sản xuất POSM, quản lý PG/PB và thi công điểm bán tốt.\n• Sẵn sàng đi công tác và di chuyển thị trường khi có yêu cầu.",
    requirementsEn: "• Bachelor's Degree in Marketing, Business Administration, or related fields.\n• Minimum 2 years of experience in Retail/Trade Marketing within Consumer Electronics, FMCG, or Retail sectors.\n• Experience managing POSM vendors, field PG/PB promoter staff, and point-of-sale construction.\n• Willingness to travel for market field visits as required.",
    benefits: "• Lương cơ bản cạnh tranh + Phụ cấp đi lại, điện thoại.\n• Bảo hiểm sức khỏe PVI cao cấp của LG.\n• Thưởng KPI hiệu suất theo chương trình bán hàng.\n• Cơ hội đào tạo chuyên sâu về kỹ năng Trade/Retail Marketing.",
    benefitsEn: "• Competitive base salary + Travel & mobile allowances.\n• Premium PVI health insurance by LG.\n• Performance KPI bonuses based on sales campaigns.\n• Advanced professional training in Trade/Retail Marketing.",
    postedAt: "2026-08-04"
  }
];

export const initialApplications = [
  {
    id: "app-lg-1",
    jobId: "job-lg-1",
    jobTitle: "Chuyên viên Mua hàng Tập trung (Marketing Procurement Specialist)",
    jobTitleEn: "Marketing Procurement Specialist",
    company: "LG Electronics Việt Nam",
    companyEn: "LG Electronics Vietnam",
    logo: procurementIcon,
    candidateName: "Nguyen Van An",
    email: "an.nguyen@gmail.com",
    phone: "0901234567",
    yearsOfExperience: "3 - 5 năm",
    experienceSummary: "4 năm kinh nghiệm Buyer Hạng mục POSM & Agency sự kiện tại Tập đoàn Bán lẻ",
    cvFileName: "CV_Nguyen_Van_An_Procurement.pdf",
    coverLetter: "Tôi có 4 năm kinh nghiệm làm mua hàng cho các hoạt động Marketing tại các tập đoàn bán lẻ lớn, rất mong muốn có cơ hội cống hiến cho LG.",
    coverLetterEn: "I have 4 years of procurement experience in Marketing categories for major retail corporations, eagerly looking forward to contributing to LG Electronics.",
    appliedAt: "2026-08-04",
    status: "Pending"
  },
  {
    id: "app-lg-2",
    jobId: "job-lg-2",
    jobTitle: "Chuyên viên Digital Marketing",
    jobTitleEn: "Digital Marketing Specialist",
    company: "LG Electronics Việt Nam",
    companyEn: "LG Electronics Vietnam",
    logo: digitalMarketingIcon,
    candidateName: "Phan Thi Binh",
    email: "binh.phan@gmail.com",
    phone: "0987654321",
    yearsOfExperience: "3 - 5 năm",
    experienceSummary: "3 năm kinh nghiệm chạy Quảng cáo số Performance Ads (Google, Meta, TikTok)",
    cvFileName: "Phan_Thi_Binh_Digital_MKT_Resume.pdf",
    coverLetter: "Em ứng tuyển vị trí Digital Marketing để đồng hành cùng sự phát triển của các dòng sản phẩm gia dụng thông minh LG tại Việt Nam.",
    coverLetterEn: "I am applying for the Digital Marketing role to drive the growth of LG smart home appliance lineups in Vietnam.",
    appliedAt: "2026-08-04",
    status: "Shortlisted"
  }
];
